// Coin Constants

// Admin: Coin Management
export const GET_ALL_USERS_KEYS_AND_COINS_REQUEST = 'GET_ALL_USERS_KEYS_AND_COINS_REQUEST';
export const GET_ALL_USERS_KEYS_AND_COINS_SUCCESS = 'GET_ALL_USERS_KEYS_AND_COINS_SUCCESS';
export const GET_ALL_USERS_KEYS_AND_COINS_FAIL = 'GET_ALL_USERS_KEYS_AND_COINS_FAIL';

// User: Coin Actions
export const GET_USER_COINS_REQUEST = 'GET_USER_COINS_REQUEST';
export const GET_USER_COINS_SUCCESS = 'GET_USER_COINS_SUCCESS';
export const GET_USER_COINS_FAIL = 'GET_USER_COINS_FAIL';

export const GET_USER_KEYS_REQUEST = 'GET_USER_KEYS_REQUEST';
export const GET_USER_KEYS_SUCCESS = 'GET_USER_KEYS_SUCCESS';
export const GET_USER_KEYS_FAIL = 'GET_USER_KEYS_FAIL';

export const REDEEM_COIN_FOR_ALL_MATCHES_REQUEST = 'REDEEM_COIN_FOR_ALL_MATCHES_REQUEST';
export const REDEEM_COIN_FOR_ALL_MATCHES_SUCCESS = 'REDEEM_COIN_FOR_ALL_MATCHES_SUCCESS';
export const REDEEM_COIN_FOR_ALL_MATCHES_FAIL = 'REDEEM_COIN_FOR_ALL_MATCHES_FAIL';

export const REDEEM_SHARED_COIN_REQUEST = 'REDEEM_SHARED_COIN_REQUEST';
export const REDEEM_SHARED_COIN_SUCCESS = 'REDEEM_SHARED_COIN_SUCCESS';
export const REDEEM_SHARED_COIN_FAIL = 'REDEEM_SHARED_COIN_FAIL';

export const CHECK_COIN_EXPIRY_REQUEST = 'CHECK_COIN_EXPIRY_REQUEST';
export const CHECK_COIN_EXPIRY_SUCCESS = 'CHECK_COIN_EXPIRY_SUCCESS';
export const CHECK_COIN_EXPIRY_FAIL = 'CHECK_COIN_EXPIRY_FAIL';

export const CLEAR_EXPIRED_COIN__REQUEST = 'CLEAR_EXPIRED_COIN__REQUEST';
export const CLEAR_EXPIRED_COIN__SUCCESS = 'CLEAR_EXPIRED_COIN__SUCCESS';
export const CLEAR_EXPIRED_COIN__FAIL = 'CLEAR_EXPIRED_COIN__FAIL';

// Action Type for Clearing Errors
export const CLEAR_EXPIRED_COIN_REQUEST = 'CLEAR_EXPIRED_COIN_REQUEST';
export const CLEAR_EXPIRED_COIN_SUCCESS = 'CLEAR_EXPIRED_COIN_REQUEST';
export const CLEAR_EXPIRED_COIN_FAIL = 'CLEAR_EXPIRED_COIN_REQUEST';


