// Constants for fetching matches
export const GET_MATCHES_REQUEST = 'GET_MATCHES_REQUEST';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';
export const GET_MATCHES_FAIL = 'GET_MATCHES_FAIL';

// Constants for fetching a single match by eventId
export const GET_MATCH_BY_ID_REQUEST = 'GET_MATCH_BY_ID_REQUEST';
export const GET_MATCH_BY_ID_SUCCESS = 'GET_MATCH_BY_ID_SUCCESS';
export const GET_MATCH_BY_ID_FAIL = 'GET_MATCH_BY_ID_FAIL';

export const GET_TENNIS_MATCHES_REQUEST = "GET_TENNIS_MATCHES_REQUEST";
export const GET_TENNIS_MATCHES_SUCCESS = "GET_TENNIS_MATCHES_SUCCESS";
export const GET_TENNIS_MATCHES_FAIL = "GET_TENNIS_MATCHES_FAIL";

export const GET_SOCCER_MATCHES_REQUEST = "GET_SOCCER_MATCHES_REQUEST";
export const GET_SOCCER_MATCHES_SUCCESS = "GET_SOCCER_MATCHES_SUCCESS";
export const GET_SOCCER_MATCHES_FAIL = "GET_SOCCER_MATCHES_FAIL";

// Admin: Select/Unselect a Match
export const UPDATE_MATCH_SELECTED_STATUS_REQUEST = 'UPDATE_MATCH_SELECTED_STATUS_REQUEST';
export const UPDATE_MATCH_SELECTED_STATUS_SUCCESS = 'UPDATE_MATCH_SELECTED_STATUS_SUCCESS';
export const UPDATE_MATCH_SELECTED_STATUS_FAIL = 'UPDATE_MATCH_SELECTED_STATUS_FAIL';

// Admin: Set Custom Admin Status for a Match
export const UPDATE_MATCH_ADMIN_STATUS_REQUEST = 'UPDATE_MATCH_ADMIN_STATUS_REQUEST';
export const UPDATE_MATCH_ADMIN_STATUS_SUCCESS = 'UPDATE_MATCH_ADMIN_STATUS_SUCCESS';
export const UPDATE_MATCH_ADMIN_STATUS_FAIL = 'UPDATE_MATCH_ADMIN_STATUS_FAIL';
// Constants for fetching Betfair odds for a specific runner
export const GET_BETFAIR_ODDS_FOR_RUNNER_REQUEST = 'GET_BETFAIR_ODDS_FOR_RUNNER_REQUEST';
export const GET_BETFAIR_ODDS_FOR_RUNNER_SUCCESS = 'GET_BETFAIR_ODDS_FOR_RUNNER_SUCCESS';
export const GET_BETFAIR_ODDS_FOR_RUNNER_FAIL = 'GET_BETFAIR_ODDS_FOR_RUNNER_FAIL';

// Constants for fetching scoreboard data by eventId
export const GET_SCOREBOARD_BY_EVENT_ID_REQUEST = 'GET_SCOREBOARD_BY_EVENT_ID_REQUEST';
export const GET_SCOREBOARD_BY_EVENT_ID_SUCCESS = 'GET_SCOREBOARD_BY_EVENT_ID_SUCCESS';
export const GET_SCOREBOARD_BY_EVENT_ID_FAIL = 'GET_SCOREBOARD_BY_EVENT_ID_FAIL';

// Constants for fetching match details with tips
export const GET_MATCH_DETAILS_WITH_TIP_REQUEST = 'GET_MATCH_DETAILS_WITH_TIP_REQUEST';
export const GET_MATCH_DETAILS_WITH_TIP_SUCCESS = 'GET_MATCH_DETAILS_WITH_TIP_SUCCESS';
export const GET_MATCH_DETAILS_WITH_TIP_FAIL = 'GET_MATCH_DETAILS_WITH_TIP_FAIL';

// Constants for managing user investment
export const MANAGE_USER_INVESTMENT_REQUEST = 'MANAGE_USER_INVESTMENT_REQUEST';
export const MANAGE_USER_INVESTMENT_SUCCESS = 'MANAGE_USER_INVESTMENT_SUCCESS';
export const MANAGE_USER_INVESTMENT_FAIL = 'MANAGE_USER_INVESTMENT_FAIL';

// Constants for auto calculating Admin Betfair odds for a runner
export const AUTO_CALCULATE_ADMIN_BETFAIR_ODDS_REQUEST = 'AUTO_CALCULATE_ADMIN_BETFAIR_ODDS_REQUEST';
export const AUTO_CALCULATE_ADMIN_BETFAIR_ODDS_SUCCESS = 'AUTO_CALCULATE_ADMIN_BETFAIR_ODDS_SUCCESS';
export const AUTO_CALCULATE_ADMIN_BETFAIR_ODDS_FAIL = 'AUTO_CALCULATE_ADMIN_BETFAIR_ODDS_FAIL';

// Constants for updating Admin Laying Data for a Runner
export const UPDATE_ADMIN_LAYING_DATA_REQUEST = 'UPDATE_ADMIN_LAYING_DATA_REQUEST';
export const UPDATE_ADMIN_LAYING_DATA_SUCCESS = 'UPDATE_ADMIN_LAYING_DATA_SUCCESS';
export const UPDATE_ADMIN_LAYING_DATA_FAIL = 'UPDATE_ADMIN_LAYING_DATA_FAIL';

// Constants for viewing the latest admin laying data for a runner
export const VIEW_ADMIN_LAYING_DATA_FOR_RUNNER_LATEST_REQUEST = 'VIEW_ADMIN_LAYING_DATA_FOR_RUNNER_LATEST_REQUEST';
export const VIEW_ADMIN_LAYING_DATA_FOR_RUNNER_LATEST_SUCCESS = 'VIEW_ADMIN_LAYING_DATA_FOR_RUNNER_LATEST_SUCCESS';
export const VIEW_ADMIN_LAYING_DATA_FOR_RUNNER_LATEST_FAIL = 'VIEW_ADMIN_LAYING_DATA_FOR_RUNNER_LATEST_FAIL';

// Constants for viewing the admin laying history for a runner
export const VIEW_ADMIN_LAYING_DATA_FOR_RUNNER_HISTORY_REQUEST = 'VIEW_ADMIN_LAYING_DATA_FOR_RUNNER_HISTORY_REQUEST';
export const VIEW_ADMIN_LAYING_DATA_FOR_RUNNER_HISTORY_SUCCESS = 'VIEW_ADMIN_LAYING_DATA_FOR_RUNNER_HISTORY_SUCCESS';
export const VIEW_ADMIN_LAYING_DATA_FOR_RUNNER_HISTORY_FAIL = 'VIEW_ADMIN_LAYING_DATA_FOR_RUNNER_HISTORY_FAIL';

// Constants for editing admin laying data for a runner
export const EDIT_ADMIN_LAYING_DATA_FOR_RUNNER_REQUEST = 'EDIT_ADMIN_LAYING_DATA_FOR_RUNNER_REQUEST';
export const EDIT_ADMIN_LAYING_DATA_FOR_RUNNER_SUCCESS = 'EDIT_ADMIN_LAYING_DATA_FOR_RUNNER_SUCCESS';
export const EDIT_ADMIN_LAYING_DATA_FOR_RUNNER_FAIL = 'EDIT_ADMIN_LAYING_DATA_FOR_RUNNER_FAIL';

// Constants for deleting admin laying data for a runner
export const DELETE_ADMIN_LAYING_DATA_FOR_RUNNER_REQUEST = 'DELETE_ADMIN_LAYING_DATA_FOR_RUNNER_REQUEST';
export const DELETE_ADMIN_LAYING_DATA_FOR_RUNNER_SUCCESS = 'DELETE_ADMIN_LAYING_DATA_FOR_RUNNER_SUCCESS';
export const DELETE_ADMIN_LAYING_DATA_FOR_RUNNER_FAIL = 'DELETE_ADMIN_LAYING_DATA_FOR_RUNNER_FAIL';

// Constants for generating auto odds
export const GENERATE_AUTO_ODDS_REQUEST = 'GENERATE_AUTO_ODDS_REQUEST';
export const GENERATE_AUTO_ODDS_SUCCESS = 'GENERATE_AUTO_ODDS_SUCCESS';
export const GENERATE_AUTO_ODDS_FAIL = 'GENERATE_AUTO_ODDS_FAIL';

// Action Type for Clearing Errors
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// ✅ New Constants

// Add Admin Betfair Odds
export const ADD_ADMIN_BETFAIR_ODDS_REQUEST = 'ADD_ADMIN_BETFAIR_ODDS_REQUEST';
export const ADD_ADMIN_BETFAIR_ODDS_SUCCESS = 'ADD_ADMIN_BETFAIR_ODDS_SUCCESS';
export const ADD_ADMIN_BETFAIR_ODDS_FAIL = 'ADD_ADMIN_BETFAIR_ODDS_FAIL';

// Get User Match Odds and Investment
export const GET_USER_MATCH_ODDS_INVESTMENT_REQUEST = 'GET_USER_MATCH_ODDS_INVESTMENT_REQUEST';
export const GET_USER_MATCH_ODDS_INVESTMENT_SUCCESS = 'GET_USER_MATCH_ODDS_INVESTMENT_SUCCESS';
export const GET_USER_MATCH_ODDS_INVESTMENT_FAIL = 'GET_USER_MATCH_ODDS_INVESTMENT_FAIL';

// User Add Investment
export const USER_UPDATE_ODDS_REQUEST = 'USER_UPDATE_ODDS_REQUEST';
export const USER_UPDATE_ODDS_SUCCESS = 'USER_UPDATE_ODDS_SUCCESS';
export const USER_UPDATE_ODDS_FAIL = 'USER_UPDATE_ODDS_FAIL';

export const USER_ADD_INVESTMENT_REQUEST = 'USER_ADD_INVESTMENT_REQUEST';
export const USER_ADD_INVESTMENT_SUCCESS = 'USER_ADD_INVESTMENT_SUCCESS';
export const USER_ADD_INVESTMENT_FAIL = 'USER_ADD_INVESTMENT_FAIL';
