// Plan Constants

// Admin: Plan Management
export const ADD_PLAN_REQUEST = 'ADD_PLAN_REQUEST';
export const ADD_PLAN_SUCCESS = 'ADD_PLAN_SUCCESS';
export const ADD_PLAN_FAIL = 'ADD_PLAN_FAIL';

export const GET_ALL_PLANS_REQUEST = 'GET_ALL_PLANS_REQUEST';
export const GET_ALL_PLANS_SUCCESS = 'GET_ALL_PLANS_SUCCESS';
export const GET_ALL_PLANS_FAIL = 'GET_ALL_PLANS_FAIL';

export const GET_PLAN_BY_ID_REQUEST = 'GET_PLAN_BY_ID_REQUEST';
export const GET_PLAN_BY_ID_SUCCESS = 'GET_PLAN_BY_ID_SUCCESS';
export const GET_PLAN_BY_ID_FAIL = 'GET_PLAN_BY_ID_FAIL';

export const EDIT_PLAN_REQUEST = 'EDIT_PLAN_REQUEST';
export const EDIT_PLAN_SUCCESS = 'EDIT_PLAN_SUCCESS';
export const EDIT_PLAN_FAIL = 'EDIT_PLAN_FAIL';

export const DELETE_PLAN_REQUEST = 'DELETE_PLAN_REQUEST';
export const DELETE_PLAN_SUCCESS = 'DELETE_PLAN_SUCCESS';
export const DELETE_PLAN_FAIL = 'DELETE_PLAN_FAIL';

// User: Plan Actions
export const SELECT_PLAN_REQUEST = 'SELECT_PLAN_REQUEST';
export const SELECT_PLAN_SUCCESS = 'SELECT_PLAN_SUCCESS';
export const SELECT_PLAN_FAIL = 'SELECT_PLAN_FAIL';

export const CHECK_PLAN_EXPIRATION_REQUEST = 'CHECK_PLAN_EXPIRATION_REQUEST';
export const CHECK_PLAN_EXPIRATION_SUCCESS = 'CHECK_PLAN_EXPIRATION_SUCCESS';
export const CHECK_PLAN_EXPIRATION_FAIL = 'CHECK_PLAN_EXPIRATION_FAIL';

export const CLEAR_EXPIRED_PLANS_REQUEST = 'CLEAR_EXPIRED_PLANS_REQUEST';
export const CLEAR_EXPIRED_PLANS_SUCCESS = 'CLEAR_EXPIRED_PLANS_SUCCESS';
export const CLEAR_EXPIRED_PLANS_FAIL = 'CLEAR_EXPIRED_PLANS_FAIL';
