// Create Transaction
export const CREATE_TRANSACTION_REQUEST = 'CREATE_TRANSACTION_REQUEST';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_FAIL = 'CREATE_TRANSACTION_FAIL';

// Update Transaction Status (Admin)
export const UPDATE_TRANSACTION_STATUS_REQUEST = 'UPDATE_TRANSACTION_STATUS_REQUEST';
export const UPDATE_TRANSACTION_STATUS_SUCCESS = 'UPDATE_TRANSACTION_STATUS_SUCCESS';
export const UPDATE_TRANSACTION_STATUS_FAIL = 'UPDATE_TRANSACTION_STATUS_FAIL';

// Get User Transactions (User Side)
export const USER_TRANSACTIONS_REQUEST = 'USER_TRANSACTIONS_REQUEST';
export const USER_TRANSACTIONS_SUCCESS = 'USER_TRANSACTIONS_SUCCESS';
export const USER_TRANSACTIONS_FAIL = 'USER_TRANSACTIONS_FAIL';

// Get All User Transactions (Admin Side)
export const ALL_USER_TRANSACTIONS_REQUEST = 'ALL_USER_TRANSACTIONS_REQUEST';
export const ALL_USER_TRANSACTIONS_SUCCESS = 'ALL_USER_TRANSACTIONS_SUCCESS';
export const ALL_USER_TRANSACTIONS_FAIL = 'ALL_USER_TRANSACTIONS_FAIL';

// Action Type for Clearing Errors
export const CLEAR_ERRORS = 'CLEAR_ERRORS';